### PR TITLE
Updated API URLs

### PR DESCRIPTION
**Pull request by snerd9334**
The forum post linked in this file now specifies new API URLs to use. I have updated the file to reflect this. Thought you might want it updated in your master branch.

### CODE REVIEW

**Comment by mattdy** [comment]
Thanks for the PR - can you just confirm that the URLs are correct? I don't seem to be able to resolve anything at that domain.

**Comment by snerd9334** [comment]
Sorry, hadn't tested them, just updated based on the post here: https://radarspotting.com/forum/index.php?topic=6117.0

Don't suppose you know of any other sources?

**Comment by mattdy** [comment]
Yes, I'd seen that post previously, but unfortunately doesn't look like this API is online any more.

I'm not aware of any other sources for this data, but if you do find any please do submit another PR!

**Comment by snerd9334** [comment]
I contacted Josh. The API is now back online (subject to global DNS resolution) so this PR should now be valid. He is also working on updating the database.

**Pull request closed without merging**
